// <auto-generated />
using System;
using CarAdverts.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarAdverts.Infrastructure.Migrations
{
    [DbContext(typeof(CarAdvertContext))]
    [Migration("20190216220329_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarAdverts.Domain.CarAdvert.CarAdvert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("Fuel");

                    b.Property<int?>("Mileage");

                    b.Property<bool>("New");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("CarAdverts");
                });

            modelBuilder.Entity("CarAdverts.Domain.CarAdvert.CarAdvert", b =>
                {
                    b.OwnsOne("CarAdverts.Domain.CarAdvert.RegistrationDate", "FirstRegistration", b1 =>
                        {
                            b1.Property<Guid>("CarAdvertId");

                            b1.Property<DateTime?>("Date")
                                .HasColumnName("FirstRegistration")
                                .HasColumnType("date");

                            b1.HasKey("CarAdvertId");

                            b1.ToTable("CarAdverts");

                            b1.HasOne("CarAdverts.Domain.CarAdvert.CarAdvert")
                                .WithOne("FirstRegistration")
                                .HasForeignKey("CarAdverts.Domain.CarAdvert.RegistrationDate", "CarAdvertId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
